jobs: 45
cluster: 
    mkdir -p logs/slurm_logs/{rule}/ &&
    sbatch
    --partition={resources.partition}
    --mem={resources.mem}
    --time={resources.time}
    --cpus-per-task={resources.threads}
    --job-name={rule}-{wildcards}
    --output=logs/slurm_logs/{rule}/{rule}-{wildcards}-%j.out
default-resources: 
  - threads=1
  - time="06:00:00"
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
rerun-incomplete: True
printshellcmds: True
scheduler: greedy